### ISSUE TITLE
test image

### ISSUE THREAD

**Issue by tonyzzzt** [htzheng/ECCV2018_CrossNet_RefSR#1]
if I want to test a single image on this network,how to do it?

**Comment by htzheng** [comment]
Hi @tonyzzzt , sorry for the inconvenience! I upload a snapshot trained by FLower dataset at Google drive,
https://drive.google.com/file/d/14rWcv1ZFyq5n4cNxjsN0fKd_62pYoz4j/view?usp=sharing

before forwarding the network, the snapshot could be loaded with using 
`net.load_state_dict(torch.load('CP185000.pth'))`

Feel free to contact me if it does not work.

**Comment by tonyzzzt** [comment]
Hello ! When I test the modified net on my own data set, there is a difference in brightness between the output image and the original image. Will this difference disappear with the iteration of the network?

**Comment by htzheng** [comment]
Sorry for the delayed reply. I preprocessed the images by scaling the range
to [0,1]. I guess that might cause the brightness difference. In addition,
this network would work well after training for small displacement (~20
pixels as the max displacement be in the Flower dataset). For large
displacement, one could coarsely align the reference image using optical
flows.

**Comment by chengxuhou** [comment]
hei

**Comment by jxingm** [comment]
Hi, can you tell me how to test an image ? I have downloaded the pth file.
