### ISSUE TITLE
About Network Structure

### ISSUE THREAD

**Issue by qibao77** [htzheng/ECCV2018_CrossNet_RefSR#2]
I am very interested in your work, but I have some confusion about the structure. Since super-resolution is a pixel-level task, the down-sampling operation of encoder in U-Net[44] structure will result in loss of information and should be avoided as much as possible. Why do you think it can be applied to SR? Thank you!

**Comment by htzheng** [comment]
Thank you for your interest! In this work, the SR problem is cast as a
two-image fusion problem solving by the U-Net structure. It can be argued
that the first few conv layers of U-Net's encoder will preserve
high-frequency details. In the preliminary experiment, I found the network
in the paper is better than concatenate two images and pass through 4 conv
layers. My guess is that the high-level information is helpful for
detecting occlusion mask therefore beneficial for fusion.

However, exploring better network structure is an interesting question. And
there could be a better network structure for this specific task.

**Comment by qibao77** [comment]
Thank you for your patient answer. Another problem is how to handle odd-sized input images, since the down-scale or up-scale factor of the encoder and decoder is fixed.

**Comment by htzheng** [comment]
@qibao77 It's easy to pad the odd-sized image with additional zeros before down-scale and up-scale.
