### ISSUE TITLE
No module named PWCNet

### ISSUE THREAD

**Issue by iamheejae** [htzheng/ECCV2018_CrossNet_RefSR#3]
Hi, i am very interested in your paper and codes. 

However, whenever i try to train image with your code, the following errors come out. 
"No module nameed PWCNet"

I thought the PWCNet is necessary for training, since your paper mentioned that 'Flownet', which contains PWCNet module, works for computing optical flow between light-field data. So I installed module name but it doesn't work with same error as i mentioned above. 

Also, looking over your codes, i found that PWCNet is only written in '__init__.py'. So I wonder if this module really needs to run your code, or if i have to install this module, how can i fix this problem?

**Comment by htzheng** [comment]
Sorry for the messed code... In this implementation, we use the FlowNet to generate flow as also mentioned in the paper. The PWCNet is not necessary and can be commented off.

**Comment by htzheng** [comment]
Will try to organize the code after this month...

**Comment by iamheejae** [comment]
@htzheng 
Thanks for your quick answer.
I also hope to get new-organized code after this month.
